---
# Variable setup.
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"


# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Configure Jenkins init settings.
- include: settings.yml

# Make sure Jenkins starts, then configure Jenkins.
- name: Ensure Jenkins is started and runs on startup.
  service: 
    name=jenkins 
    state=restarted 
    enabled=yes

- name: Get the jenkins-cli jarfile from the Jenkins server.
  get_url: 
    url: http://localhost:8080/jnlpJars/jenkins-cli.jar 
    dest: "{{ jenkins_jar_location }}"
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 10
  check_mode: no

- name: Jenkins | Plugins
  include: "plugins.yml"

# Create  SSH key for user jenkins
- name: Create ssh key for jenkins user
  user: name=jenkins generate_ssh_key=yes  shell=/bin/bash